### ISSUE TITLE
[Feature Request] Keychron C1

### ISSUE THREAD

**Issue by mywynne** [qmk/qmk.fm_old#149]
### Description

Would love to see Keychron supported! Specifically a C1 for me (it has an unmappable Siri/Cortana key).

**Comment by noroadsleft** [comment]
For Keychron C1 support, your best bet in my opinion would be asking here:

* [Consider adding Keychron K* keyboards · Issue #7370 · qmk/qmk_firmware](https://github.com/qmk/qmk_firmware/issues/7370)

The issue is oriented toward the K-series boards, but the users there will be more familiar with the Keychron hardware.

**Comment by c---** [comment]
The [SonixQMK](https://github.com/SonixQMK/qmk_firmware) project has support for the C1 and other boards not in qmk proper.

I guess the main issue is that boards like the C1 are not currently officially supported by the manufacturer so I don't know if they will get integrated in the main source like the Q1 is.
