### ISSUE TITLE
NT980 Keyboard Firmware

### ISSUE THREAD

**Issue by jamsuya** [qmk/qmk.fm_old#150]
### Information

- [X] None of the other issue templates apply

### Description

I recently bought a new keyboard from [Aliexpress](https://www.aliexpress.com/item/1005003603414928.html) called the NT980. When I plugged initially plugged it into my computer, it worked perfectly fine, RGB and all. The only problem I ran into was that it wasn't being detected by VIA, and it was advertised that it supported VIA. Looking up the supported firmware, I saw there was a folder named NT980 from Evyd13, thinking that was the firmware I needed to flash onto my keyboard to fix the problem. After flashing that firmware, the keyboard ceased to work, and I can't find the correct firmware in order to fix my problem.
Let me know what can be done :) Thank you guys.

**Comment by noroadsleft** [comment]
The images on that Aliexpress listing show the following screenshot, which shows the board identification as `NA98` (top right of the VIA screen, highlighted in red):

![image](https://user-images.githubusercontent.com/18669334/154392002-b291375e-e2b0-4101-aa4b-ae0d822a1326.png)

That tells me this isn't an `evyd13/nt980`, which would actually show `NT980` in VIA.

If you have a multimeter and can take the keyboard apart, you could probably trace the matrix and get the board working in QMK again.

Otherwise, your best bet is to contact the vendor and ask for two things: 1) The default `.hex` or `.bin` that comes flashed to the board, ***and*** 2) the VIA `.json` file that enables the board to be configured by VIA.

Sadly, with a lot of Aliexpress vendors, they're either not good or flat-out refuse to provide source code that can be compiled, which limits QMK's ability as an organization to support the board, unless one of our members actually buys the board (and we don't have unlimited resources for doing something like that).
